config/routes.rb
Rails.application.routes.draw do

  get 'gread/index'

  get 'admin/course'
  get 'admin/video'
  get 'admin/test'
  get 'admin/addcourse'
  get 'admin/user'

  resources :courses do
    resources :videos
  end

  resources :videos do 
    resources :tests
  end

  resources :users
  resources :signups
  resources :logups

root 'courses#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :videos, dependent: :destroy
	validates :title, presence: true
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :pwd, presence: true,
                    length: { minimum: 5 }
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
  has_many :tests
  validates :title, :teacher, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "123456"
	def course
		@courses = Course.all
	end

	def video
		@courses = Course.all
	end

	def test	
		@videos = Video.all
	end

	def addcourse
		@course = Course.new
	end

	def user
		@user = User.all
	end

end
	

app/controllers/gread_controller.rb
class GreadController < ApplicationController
  def index
  end
end

app/controllers/logups_controller.rb
class LogupsController < ApplicationController
	def new
		@logup = User.new
	end

	def create
		@logup = User.new(user_params)

		if @logup.save
			redirect_to admin_user_path
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :pwd)	
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	def index
		@tests = Test.where("video_id = ?", params[:video_id])
		if @tests.exists?
			@title = @tests.first.video.title
		else
			redirect_to videos_path
		end
	end

	def new
		@video = Video.find(params[:video_id])
		@test = @video.tests.new
	end

	def create
		@video = Video.find(params[:video_id])
		if @test = @video.tests.create(test_params)
			redirect_to admin_test_path
		else
			render 'new'
		end
	end

	def show
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
	end

	def edit
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
	end

	def update
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
		if @test.update(test_params)
			redirect_to admin_test_path
		else
			redirect_to admin_test_path
		end
	end

	def destroy
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
		@test.destroy
		redirect_to admin_test_path
	end

private
	def test_params
		params.require(:test).permit(:problem, :option_a, :option_b, :option_c, :option_d, :answer, :score)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		if @user = User.exists?(user_params)
			redirect_to videos_path
		else
			redirect_to new_user_path
		end
	end

	def index
		@user = User.all
	end

def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
 
  if @user.update(user_params)
    redirect_to admin_user_path
  else
    render 'edit'
  end
end

    def destroy
    @user = User.find(params[:id])
    @user.destroy

   redirect_to admin_user_path
    end
	private
		def user_params
			params.require(:user).permit(:name, :pwd)	
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		@course = Course.all
	end

	def new
		@course  = Course.find(params[:course_id])
		@video = @course.videos.new
	end

	def create
		@course  = Course.find(params[:course_id])
		if @video = @course.videos.create(video_params)
			redirect_to admin_video_path
		else
			render course_path(@course)
		end
	end

	def show
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
	end

	def destroy
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
		@video.destroy
		redirect_to admin_video_path
	end

	def edit
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
	end

	def update
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
		if @video.update(video_params)
			redirect_to admin_video_path
		else
			redirect_to course_path(@course)
		end
	end

	private
		def video_params
			params.require(:video).permit(:title, :teacher)
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/gread_helper.rb
module GreadHelper
end

app/helpers/logup_helper.rb
module LogupHelper
end

app/helpers/logups_helper.rb
module LogupsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/admin/_nav.html.erb
<ul class="nav nav-pills nav-justified">
<li role="presentation" class="<%= "active" if params[:action] == 'user'%>">
		<%= link_to "用户", admin_user_path %>
	</li>
	<li role="presentation" class="<%= "active" if params[:action] == 'course'%>">
		<%= link_to "课程", admin_course_path %>
	</li>
	<li role="presentation" class="<%= "active" if params[:action] == 'video'%>">
		<%= link_to "类目", admin_video_path %>
	</li>
	<li role="presentation" class="<%= "active" if params[:action] == 'test'%>">
		<%= link_to "测试", admin_test_path %>
	</li>
</ul>

app/views/admin/addcourse.html.erb
<div class="container main-content">
	<br>
	<br>
	<%= simple_form_for :course, url: courses_path do |f| %>
	
	<% if @course.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@course.errors.count, "error") %> prohibited
				this course from being saved:</h2>
			<ul>
				<% @course.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.input :title, label: '课程名' %>
	</p>

	<p>
		<%= f.button :submit %>
	</p>
	<% end %>

	<%= link_to '返回', admin_course_path %>

</div>

app/views/admin/course.html.erb
<div class="container main-content">
	<%= render partial:"admin/nav"%>
	
	<br>
	<br>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th>课程名</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @courses.each do |course|%>
			<tr>
				<th><%= course.id %></th>
				<td><%= course.title %></td>
				<td style="width:130px;">
					<%= link_to "编辑", edit_course_path(course), class:"btn btn-warning" %>
					<%= link_to "删除", course_path(course), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to "新增课程", admin_addcourse_path, class:"btn btn-primary" %>
</div>

app/views/admin/test.html.erb
<div class="container main-content">
	<%= render partial:"admin/nav"%>
	<br>
	<br>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>类目名</th>
				<th>测试题</th>
			</tr>
		</thead>
		<tbody>
			<% @videos.each do |video|%>
				<tr>
					<th>	
						<%= video.title %><br><br>
						<%= link_to "新增测试题", new_video_test_path(video) , class:"btn btn-primary"%>
					</th>
					<td style="padding:0;">
						<table class="table table-condensed table-bordered" style="margin:0;">
							<tbody>
								<% video.tests.each do |test| %>
								<tr>
									<td><%= test.problem %></td>
									<td><%= test.option_a %></td>
									<td><%= test.option_b %></td>
									<td><%= test.option_c %></td>
									<td><%= test.option_d %></td>
									<td><%= test.answer %></td>
									<td><%= test.score %></td>
									<td><%= video.teacher %></td>
									<td><%= link_to "编辑", [:edit, test.video, test], class:"btn btn-warning" %></td>
									<td><%= link_to "删除", [test.video, test], method: :delete, data: {confirm: "Are you sure?"} , class:"btn btn-danger"%></td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admin/user.html.erb
<div class="container main-content">
	<%= render partial:"admin/nav"%>
	
	<br>
	<br>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>#</th>
				<th>用户</th>
				<th>操作</th>
			</tr>
		</thead>
		<tbody>
			<% @user.each do |user|%>
			<tr>
				<th><%= user.name %></th>
				<td><%= user.pwd %></td>
				<td style="width:130px;">
					<%= link_to "编辑", edit_user_path(user), class:"btn btn-warning" %>
					<%= link_to "删除", user_path(user), method: :delete, data: {confirm: "Are you sure?"}, class:"btn btn-danger" %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<%= link_to "新增用户", new_logup_path, class:"btn btn-primary" %>
</div>

app/views/admin/video.html.erb
<div class="container main-content">
	<%= render partial:"admin/nav"%>	
	<br>
	<br>
	<table class="table table-striped table-bordered">
		<thead>
			<tr>
				<th>课程名</th>
				<th>类目</th>
				

			</tr>
		</thead>
		<tbody>
			<% @courses.each do |course|%>
				<tr>
					<th>
						《<%= course.title %>》<br><br>
						<%= link_to "新增类目", course_path(course), class:"btn btn-primary"%>
					</th>
					<td style="padding:0;">
						<table class="table table-condensed table-bordered" style="margin:0;">
							<tbody>
								<% course.videos.each do |video| %>
								<tr>
									<td><%= video.title %></td>
									<td><%= video.teacher %></td>
									<td><%= link_to "编辑", [:edit, video.course, video], class:"btn btn-warning" %></td>
									<td><%= link_to "删除", [video.course, video], method: :delete, data: {confirm: "Are you sure?"} , class:"btn btn-danger"%>
									</td>
								</tr>
								<% end %>
							</tbody>
						</table>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Education</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<!--in order to display user page better -->
<div class="<%= "vbox" if params[:controller] == "users"%>">
	<!--navbar-->
	<%= render partial:"share/topbar"%>

	<%= yield %>	
</div>
<!--footer-->
<div class="<%= "container" if params[:controller] != "users"%>">
	<div class="<%= "row" if params[:controller] != "users"%>">
		<div class="write-row"></div>
		<%= render partial: "share/footer"%>		
	</div>
</div>

</body>
</html>

app/views/share/_footer.html.erb
<div class="footer text-center">
	<%= link_to "关于我们", "#"%>
	<span>|</span>
	<%= link_to "联系我们", "#"%>
	<h5>Copyright © 2015安庆师范学院计算机石贤辉</h5>
</div>

app/views/share/_topbar.html.erb
<nav class="navbar navbar-default topbar">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to " 在 线 考 试 ", courses_path, class:"navbar-brand title" %>
		</div>

		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav">
				<li><%= image_tag "01index-en.png", class:"info" %></li>
			</ul>
			<form class="navbar-form navbar-right topform" role="search">
				<label class="sign" for="search">
					<span><%= link_to '登录', new_user_path %></span> |
					<span><%= link_to '注册', new_user_path %></span>
				</label><br>
				<div class="input-group">
					<input type="text" class="form-control">
					<span class="input-group-btn">
						<button class="btn btn-info" type="button">
							<span class="glyphicon glyphicon-search"></span>
						</button>
					</span>
				</div>
			</form>
		</div>
	</div>
</nav>
<div class="write-row"></div>