config/routes.rb
Rails.application.routes.draw do

  get 'gread/index'

  get 'admin/course'
  get 'admin/video'
  get 'admin/test'
  get 'admin/addcourse'
  get 'admin/user'

  resources :courses do
    resources :videos
  end

  resources :videos do 
    resources :tests
  end

  resources :users
  resources :signups
  resources :logups

root 'courses#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :videos, dependent: :destroy
	validates :title, presence: true
end

app/models/test.rb
class Test < ActiveRecord::Base
  belongs_to :video
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :pwd, presence: true,
                    length: { minimum: 5 }
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :course
  has_many :tests
  validates :title, :teacher, presence: true
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "123456"
	def course
		@courses = Course.all
	end

	def video
		@courses = Course.all
	end

	def test	
		@videos = Video.all
	end

	def addcourse
		@course = Course.new
	end

	def user
		@user = User.all
	end

end
	

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
			redirect_to admin_course_path
		else
			render admin_addcourse_path
		end
	end

	def show
		@course = Course.find(params[:id])
	end

	def edit
		@course = Course.find(params[:id])	
	end

	def update
		@course = Course.find(params[:id])

		if @course.update(course_params)
			redirect_to admin_course_path
		else
			render admin_edit_path
		end
	end

	def destroy
		@course = Course.find(params[:id])
		@course.destroy
		 redirect_to admin_course_path
	end
	
	private
		def course_params
		params.require(:course).permit(:title)
		end
end

app/controllers/gread_controller.rb
class GreadController < ApplicationController
  def index
  end
end

app/controllers/logups_controller.rb
class LogupsController < ApplicationController
	def new
		@logup = User.new
	end

	def create
		@logup = User.new(user_params)

		if @logup.save
			redirect_to admin_user_path
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :pwd)	
	end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
	def new
		@signup = User.new
	end

	def create
		@signup = User.new(user_params)

		if @signup.save
			redirect_to new_user_path
		else
			render 'new'
		end
	end

	private
	def user_params
		params.require(:user).permit(:name, :pwd)	
	end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
	def index
		@tests = Test.where("video_id = ?", params[:video_id])
		if @tests.exists?
			@title = @tests.first.video.title
		else
			redirect_to videos_path
		end
	end

	def new
		@video = Video.find(params[:video_id])
		@test = @video.tests.new
	end

	def create
		@video = Video.find(params[:video_id])
		if @test = @video.tests.create(test_params)
			redirect_to admin_test_path
		else
			render 'new'
		end
	end

	def show
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
	end

	def edit
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
	end

	def update
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
		if @test.update(test_params)
			redirect_to admin_test_path
		else
			redirect_to admin_test_path
		end
	end

	def destroy
		@video = Video.find(params[:video_id])
		@test = @video.tests.find(params[:id])
		@test.destroy
		redirect_to admin_test_path
	end

private
	def test_params
		params.require(:test).permit(:problem, :option_a, :option_b, :option_c, :option_d, :answer, :score)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		if @user = User.exists?(user_params)
			redirect_to videos_path
		else
			redirect_to new_user_path
		end
	end

	def index
		@user = User.all
	end

def show
  	@user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
 
  if @user.update(user_params)
    redirect_to admin_user_path
  else
    render 'edit'
  end
end

    def destroy
    @user = User.find(params[:id])
    @user.destroy

   redirect_to admin_user_path
    end
	private
		def user_params
			params.require(:user).permit(:name, :pwd)	
		end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
	def index
		@course = Course.all
	end

	def new
		@course  = Course.find(params[:course_id])
		@video = @course.videos.new
	end

	def create
		@course  = Course.find(params[:course_id])
		if @video = @course.videos.create(video_params)
			redirect_to admin_video_path
		else
			render course_path(@course)
		end
	end

	def show
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
	end

	def destroy
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
		@video.destroy
		redirect_to admin_video_path
	end

	def edit
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
	end

	def update
		@course = Course.find(params[:course_id])
		@video = @course.videos.find(params[:id])
		if @video.update(video_params)
			redirect_to admin_video_path
		else
			redirect_to course_path(@course)
		end
	end

	private
		def video_params
			params.require(:video).permit(:title, :teacher)
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/gread_helper.rb
module GreadHelper
end

app/helpers/logup_helper.rb
module LogupHelper
end

app/helpers/logups_helper.rb
module LogupsHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/logups/new.html.erb
<%= simple_form_for :user, url: logups_path do |user|%>
<% if @logup.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@logup.errors.count, "error") %> prohibited
	      this user from being saved:</h2>
	    <ul>
	    <% @logup.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
<% end %>
<%= user.input :name, label: '用户名'%>
<%= user.input :pwd, label: '密码' %>
<%= user.button :submit%>
<% end %>

app/views/users/edit.html.erb
<div class="container main-content">
	<h1>Edit User</h1>

	<br>
	<br>

	<%= form_for :user, url: user_path(@user), method: :patch do |f| %>

	  <% if @user.errors.any? %>
	  <div id="error_explanation">
	    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
	      this user from being saved:</h2>
	    <ul>
	    <% @user.errors.full_messages.each do |msg| %>
	      <li><%= msg %></li>
	    <% end %>
	    </ul>
	  </div>
	  <% end %>

	  <p>
	    <%= f.label :name %><br>
	    <%= f.text_field :name %>
	  </p>

	  <p>
	    <%= f.label :pwd %><br>
	    <%= f.text_field :pwd %>
	  </p>
	 
	  <p>
	    <%= f.submit %>
	  </p>
	<% end %>

	<%= link_to '返回', admin_user_path %>
</div>

app/views/users/new.html.erb
<div class="flex vbox signin-body">
	<div class="flex"></div>
	<div class="container">
		<div class="col-md- col-md-offset-7">
			<div class="signin-main">
				<div role="tabpanel">
					<!-- Nav tabs -->
					<ul class="nav nav-tabs" role="tablist">
						<li role="presentation" class="active sign-tab"><a href="#signin" role="tab" data-toggle="tab">登录</a></li>
						<li role="presentation" class="sign-tab"><a href="#signup" role="tab" data-toggle="tab">注册</a></li>
					</ul>
					<!-- Tab panes -->
					<div class="tab-content">
						<!--登录-->
						<div role="tabpanel" class="tab-pane sign-area active" id="signin">
							<%= simple_form_for :user, url: users_path do |signin|%>
								<%= signin.input :name, label: '用户名'%>
								<%= signin.input :pwd, label: '密码' %>
								<%= signin.button :submit ,'登录',class:'forget'%>
							<% end %>
						</div>
						<!--注册-->
						<div role="tabpanel" class="tab-pane sign-area" id="signup">
							<%= simple_form_for :user, url: signups_path do |user|%>
								<%= user.input :name, label: '用户名'%>
								<%= user.input :pwd, label: '密码' %>
								<%= user.button :submit, '注册' ,class:'forget'%>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="flex"></div>
</div>	

app/views/videos/_form.html.erb
<%= form_for([@course, @course.videos.build]) do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :teacher %><br>
		<%= f.text_field :teacher %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/videos/_video.html.erb
	<p>
		<strong>Video title:</strong>
		<%= video.title %>
	</p>
	<p>
		<strong>Video introduce:</strong>
		<%= video.introduce %>
	</p>
	<p>
		<strong>Video teacher:</strong>
		<%= video.teacher %>
	</p>
	<p>
		<strong>Video poster:</strong>
		<%= video.poster %>
	</p>
	<p>
		<strong>Video video:</strong>
		<%= video.video %>
	</p>
	<p>
		<%= link_to 'Destroy Video', [video.course, video], method: :delete, data: { confirm: 'Are you sure?' } %>|
		<%= link_to 'Edit', [:edit, video.course, video] %>
	</p>

app/views/videos/edit.html.erb
<div class="container main-content">
	<%= form_for([@video.course, @video]) do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :teacher %><br>
		<%= f.text_field :teacher %>
	</p>
	<p>
		<%= f.submit %>
	</p>
	<% end %>
	<%= link_to "返回", admin_video_path %>
</div>

app/views/videos/index.html.erb
<!--test_background-->
<div class="demand-bg vbox">
	<div class="flex"></div>
	<div class="test-title text-center">
		<h1>试题选择</h1>
	</div>	
	<div class="flex"></div>
</div>
<!--demand-->

<div class="container video-list">
	<!--lessons-->
	<% @course.each do |course|%>
	<div class="list-title">
		<span class="rel">&nbsp;&nbsp;<%= course.title %>&nbsp;&nbsp;</span>
	</div>
	<div class="list-body">
		<% course.videos.each do |video|%>
		 	<%= link_to video_tests_path(video) do %>
				<h4><%= video.title %></h4>
			<% end %>
			<hr class="dot">
		<% end %>
	</div>
	<% end %>
	<div class="text-center">
		<%= button_to "查 询", "#", class: "btn btn-info btn-course", method: :get %>
	</div>
</div>

app/views/videos/show.html.erb
<!--content-->
<div class="container video">
	<div class="row">
		<div class="col-md-7 text-center">
			<video width="99.95%" height="422" class="mejs-player" poster="/assets/<%= @video.poster %>" controls="controls" preload="none">
				<source type="video/mp4" src="<%= @video.video %>" />
				<source type="video/webm" src="myvideo.webm" />
				<source type="video/ogg" src="myvideo.ogv" />
			</video>
		</div>
		<div class="col-md-5">
			<div class="introduce">
				<h2 class="text-center"><%= @video.title %></h2>
				<h3>课程介绍：</h3>
				<p class="text-justify">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @video.introduce %></p>
				<h3>讲师：</h3>
				<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<%= @video.teacher%></p>
			</div>
		</div>
	</div>
	<div class="text-center">
		<%= link_to "本科作业", video_tests_path(@video), class: "btn btn-info btn-course", role: "button" %>
		<span>&nbsp;</span>
		<%= link_to "成绩查询", "#", class: "btn btn-info btn-course", role: "button" %>
	</div>
</div>
<!--video-list-->
<div class="container video-list">
	<div class="list-title">
		<span class="rel">相关课程</span>
	</div>
	<div class="list-body">
		<%@course.videos.each do |v|%>
		<h4><span class="glyphicon glyphicon-play-circle"></span>&nbsp;&nbsp;&nbsp;&nbsp;<%= v.title %></h4>
		<hr class="dot">
		<% end %>
	</div>
</div>